### ISSUE TITLE
Problem when type hinting method process in PHP7

### ISSUE THREAD

**Issue by loicdev** [swarrot/SwarrotBundle#152]
Hi, 
we are using a PHP 7.2 stack with SwarrotBundle and we 're font of a issue that can't passed PHP CS-Fixer rules:

We need to type-hinting the processor return with `?bool` when using the middleware configurator `swarrot.processor.ack`. 

So the resposability of ack/no'ack depends on this configurator.

How can we do that without "re-create" the ack processor ?

Thanks in advance

**Comment by odolbeau** [comment]
Hi,
I don't really understand your problem.

Why do you need to type hint this processor with `?bool`?
Could you provide the PHP CS-Fixer error?

**Comment by loicdev** [comment]
Hi, 
the phpcs's suggestion : 
``` 
-    public function process(Message $message, array $options)
+    public function process(Message $message, array $options): void
``` 
because i haven't got return in the method (the ack processor do it by itself) 
i go to the method definition in vendor and i saw the return was indeed `?bool`.
I try to ack the message by myself with a return true/false but i can can't reproduce the ack processor behaviour and it failed.

At this moment, i temporary ignore my consumer file to passed the phpcs tests.

**Comment by odolbeau** [comment]
For which file does PHPCS makes you this suggestion?

* If it's for the AckProcessor shipped with `swarrot` (the lib, not the bundle) you should probably change your PHPCS configuration to analyze only files in your `src` directory.
* If it's a custom processor in your codebase, do you implements the `ProcessorInterface`? If yes, I don't understand why PHPCS suggest you to change your signature as it wouldn't respect the interface anymore.

As the complete signature of the `process` method in the `ProcessorInterface` should be:
```
public function process(Message $message, array $options): bool;
```
Don't hesitate to return a boolean in your custom processors.
We won't change the interface for now because it will result in a new major release but when we'll do it, you'll be ready. :)

**Comment by loicdev** [comment]
thanks u ;)

**Comment by stof** [comment]
And ProcessorInterface in swarrot defines `@return bool|null` in phpdoc. So that suggestion would even be wrong.
